AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - Rakefile
    - bin/**/*
    - config/environments/**/*
    - config/initializers/**/*
    - config/application.rb
    - config/puma.rb
    - db/schema.rb
    - db/migrate/**/*
    - vendor/**/*

# I've never seen this one go bad.
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 36

Metrics/BlockLength:
  Max: 45
  Exclude:
    - test/factories/incidents.rb

Metrics/ClassLength:
  Exclude:
    - app/models/incident.rb
    - test/system/completing_incidents_test.rb

# This class just has long attributes, and longer ways to generate the data.
Metrics/LineLength:
  Exclude: 
    - test/factories/incidents.rb

Metrics/MethodLength:
  Max: 18
  Exclude:
    - test/system/completing_incidents_test.rb

# 'and' and && are different. I know when I want one and when I want the other.
Style/AndOr:
  Enabled: false

# Incidents have complicated validation conditions.
Style/BlockEndNewline:
  Exclude:
    - 'app/models/incident.rb'

# It's straight from the Rails docs.
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

# Not bothering for this repo.
Style/Documentation:
  Enabled: false

# This doesn't apply to controllers, where the final render is implied.
Style/GuardClause:
  Exclude:
    - app/controllers/*

Style/IfUnlessModifier:
  Enabled: true

# The only alternative with long lambdas is to say (lambda do ... end),
# wrapped in parentheses, which looks TERRIBLE.
Style/Lambda:
  Exclude:
    - 'app/models/incident.rb'

Style/MultilineBlockLayout:
  Exclude:
    - 'app/models/incident.rb'

Style/MultilineOperationIndentation:
  Exclude:
    - 'app/models/incident.rb'

# I like to write FactoryGirl calls without parentheses.
Style/NestedParenthesizedCalls:
  Exclude:
    - test/**/*
