language: ruby
rvm: 2.4.1
env: DISPLAY=:99.0
before_script:
  - mysql -e 'create database incidents_test;'
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  - bundle exec rspec --fail-fast
branches:
  only:
    - master
notifications:
  email: false
