sudo: required
dist: trusty
language: ruby
rvm: 2.4.1
env: CODECLIMATE_REPO_TOKEN=611cda7a6df35c4ca4df08319797b6eba033ca5f61068f90072cb148f71714c8
addons:
  apt:
    sources: google-chrome
    packages: google-chrome-stable
before_script:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - export PATH=$PATH:/usr/lib/chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mysql -e 'CREATE DATABASE incidents_test;'
  - mysql -e "SET PASSWORD FOR 'travis' = PASSWORD('bananas');"
  - mysql -e "GRANT ALL PRIVILEGES on incidents_test.* TO 'travis';"
  - cp config/database.travis.yml config/database.yml
script:
  - DISABLE_SPRING=true bundle exec rails test:system
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
